# Generated by Django 3.2.6 on 2021-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trellouser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Emailid', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Description', models.CharField(max_length=2000)),
                ('Categorie_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trelloapp.categories')),
                ('Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trelloapp.trellouser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
                ('Emailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticications', to='Trelloapp.trellouser')),
                ('Username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trelloapp.trellouser')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='Username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Trelloapp.trellouser'),
        ),
    ]
