# Generated by Django 3.2.6 on 2021-09-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trelloapp', '0002_alter_task_categorie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Categorie_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trelloapp.categories'),
        ),
    ]
